/**
 * Autogenerated file. Do not modify manually.
 */
#ifndef ZOAL_MCU_ATTINY2313A_HPP
#define ZOAL_MCU_ATTINY2313A_HPP

#include <stdint.h>
#include <zoal/arch/avr/adc.hpp>
#include <zoal/arch/avr/attiny/cfg.hpp>
#include <zoal/arch/avr/attiny/irq.hpp>
#include <zoal/arch/avr/attiny/metadata.hpp>
#include <zoal/arch/avr/attiny/mux.hpp>
#include <zoal/arch/avr/port.hpp>
#include <zoal/arch/avr/timer16.hpp>
#include <zoal/arch/avr/timer8.hpp>
#include <zoal/arch/enable.hpp>
#include <zoal/arch/power.hpp>
#include <zoal/gpio/base_api.hpp>
#include <zoal/gpio/pin.hpp>
#include <zoal/gpio/port_link.hpp>
#include <zoal/mcu/base_mcu.hpp>

namespace zoal { namespace mcu {
    template<uint32_t Frequency>
    class attiny2313a : public base_mcu<Frequency, 1> {
    public:
        template<uintptr_t Address, uint8_t PinMask>
        using port = typename ::zoal::arch::avr::port<Address, PinMask>;

        using port_b = port<0x0036, 0xFF>;
        using port_d = port<0x0030, 0x7F>;
        using port_a = port<0x0039, 0x07>;

        class timer_00_mem_model {
        public:
            using word = uint8_t;

            static constexpr ptrdiff_t TCCRxA = 0x00;
            static constexpr ptrdiff_t TCNTx = 0x02;
            static constexpr ptrdiff_t TCCRxB = 0x03;
            static constexpr ptrdiff_t OCRxA = 0x06;
            static constexpr ptrdiff_t TIFRx = 0x08;
            static constexpr ptrdiff_t TIMSKx = 0x09;
            static constexpr ptrdiff_t OCRxB = 0x0C;

            static constexpr uint8_t TCCRxA_COMxA = 0xC0;
            static constexpr uint8_t TCCRxA_COMxB = 0x30;
            static constexpr uint8_t TCCRxA_WGMx = 0x03;
            static constexpr uint8_t TCCRxB_FOCxA = 0x80;
            static constexpr uint8_t TCCRxB_FOCxB = 0x40;
            static constexpr uint8_t TCCRxB_WGMx2 = 0x08;
            static constexpr uint8_t TCCRxB_CSx = 0x07;
            static constexpr uint8_t TIFRx_OCFxB = 0x04;
            static constexpr uint8_t TIFRx_TOVx = 0x02;
            static constexpr uint8_t TIFRx_OCFxA = 0x01;
            static constexpr uint8_t TIMSKx_OCIExB = 0x04;
            static constexpr uint8_t TIMSKx_TOIEx = 0x02;
            static constexpr uint8_t TIMSKx_OCIExA = 0x01;
        };

        using timer_00 = ::zoal::arch::avr::timer8<0x0050, 0, false, timer_00_mem_model>;
        class timer_01_mem_model {
        public:
            using word = uint16_t;

            static constexpr ptrdiff_t TCCRxC = 0x00;
            static constexpr ptrdiff_t ICRx = 0x02;
            static constexpr ptrdiff_t OCRxB = 0x06;
            static constexpr ptrdiff_t OCRxA = 0x08;
            static constexpr ptrdiff_t TCNTx = 0x0A;
            static constexpr ptrdiff_t TCCRxB = 0x0C;
            static constexpr ptrdiff_t TCCRxA = 0x0D;
            static constexpr ptrdiff_t TIFRx = 0x16;
            static constexpr ptrdiff_t TIMSKx = 0x17;

            static constexpr uint8_t TCCRxC_FOCxA = 0x80;
            static constexpr uint8_t TCCRxC_FOCxB = 0x40;
            static constexpr uint8_t TCCRxB_ICNCx = 0x80;
            static constexpr uint8_t TCCRxB_ICESx = 0x40;
            static constexpr uint8_t TCCRxB_WGMx = 0x18;
            static constexpr uint8_t TCCRxB_CSx = 0x07;
            static constexpr uint8_t TCCRxA_COMxA = 0xC0;
            static constexpr uint8_t TCCRxA_COMxB = 0x30;
            static constexpr uint8_t TCCRxA_WGMx = 0x03;
            static constexpr uint8_t TIFRx_TOVx = 0x80;
            static constexpr uint8_t TIFRx_OCFxA = 0x40;
            static constexpr uint8_t TIFRx_OCFxB = 0x20;
            static constexpr uint8_t TIFRx_ICFx = 0x08;
            static constexpr uint8_t TIMSKx_TOIEx = 0x80;
            static constexpr uint8_t TIMSKx_OCIExA = 0x40;
            static constexpr uint8_t TIMSKx_OCIExB = 0x20;
            static constexpr uint8_t TIMSKx_ICIEx = 0x08;
        };

        using timer_01 = ::zoal::arch::avr::timer16<0x0042, 1, timer_01_mem_model>;

        template<class Port, uint8_t Offset>
        using pin = typename ::zoal::gpio::pin<Port, Offset>;

        using pb_00 = pin<port_b, 0>;
        using pb_01 = pin<port_b, 1>;
        using pb_02 = pin<port_b, 2>;
        using pb_03 = pin<port_b, 3>;
        using pb_04 = pin<port_b, 4>;
        using pb_05 = pin<port_b, 5>;
        using pb_06 = pin<port_b, 6>;
        using pb_07 = pin<port_b, 7>;

        using pd_00 = pin<port_d, 0>;
        using pd_01 = pin<port_d, 1>;
        using pd_02 = pin<port_d, 2>;
        using pd_03 = pin<port_d, 3>;
        using pd_04 = pin<port_d, 4>;
        using pd_05 = pin<port_d, 5>;
        using pd_06 = pin<port_d, 6>;

        using pa_00 = pin<port_a, 0>;
        using pa_01 = pin<port_a, 1>;
        using pa_02 = pin<port_a, 2>;

        using port_chain = typename ::zoal::gpio::chain_builder<port_b, port_d, port_a>::chain;
        using api = ::zoal::gpio::base_api<port_chain>;
        using mux = ::zoal::arch::avr::attiny::mux<api>;
        using cfg = ::zoal::arch::avr::attiny::cfg<api, Frequency>;
        using irq = ::zoal::arch::avr::attiny::irq;

        template<class... Module>
        using power = ::zoal::arch::power<Module...>;

        template<class... Module>
        using enable = ::zoal::arch::enable<Module...>;
    };
}}

namespace zoal { namespace metadata {
    using zoal::utils::integral_constant;

}}

#endif
