/**
 * Autogenerated file. Do not modify manually.
 */
#ifndef ZOAL_MCU_STM32F303VCTX_HPP
#define ZOAL_MCU_STM32F303VCTX_HPP

#include <cstdint>
#include <zoal/arch/cortex/stm32f3/adc.hpp>
#include <zoal/arch/cortex/stm32f3/cfg.hpp>
#include <zoal/arch/cortex/stm32f3/i2c.hpp>
#include <zoal/arch/cortex/stm32f3/mux.hpp>
#include <zoal/arch/cortex/stm32f3/port.hpp>
#include <zoal/arch/cortex/stm32f3/rcc.hpp>
#include <zoal/arch/cortex/stm32f3/spi.hpp>
#include <zoal/arch/cortex/stm32f3/timer.hpp>
#include <zoal/arch/cortex/stm32f3/usart.hpp>
#include <zoal/arch/cortex/stm32x/bus_clock.hpp>
#include <zoal/arch/cortex/stm32x/metadata.hpp>
#include <zoal/arch/enable.hpp>
#include <zoal/arch/power.hpp>
#include <zoal/ct/signature.hpp>
#include <zoal/gpio/api.hpp>
#include <zoal/gpio/pin.hpp>

namespace zoal { namespace mcu {
    class stm32f303vctx {
    public:
        using self_type = stm32f303vctx;
        using signature = zoal::ct::signature<'s', 't', 'm', '3', '2', 'f', '3', '0', '3', 'v', 'c', 't', 'x'>;

        using rcc = ::zoal::arch::stm32f3::rcc<0x40021000>;

        template<uint32_t Mask>
        using clock_ahb = ::zoal::arch::stm32x::bus_clock<rcc, zoal::arch::bus::cortex_ahb, Mask>;

        template<uint32_t Mask>
        using clock_ahb1 = ::zoal::arch::stm32x::bus_clock<rcc, zoal::arch::bus::cortex_ahb1, Mask>;

        template<uint32_t Mask>
        using clock_ahb2 = ::zoal::arch::stm32x::bus_clock<rcc, zoal::arch::bus::cortex_ahb2, Mask>;

        template<uint32_t Mask>
        using clock_apb1 = ::zoal::arch::stm32x::bus_clock<rcc, zoal::arch::bus::cortex_apb1, Mask>;

        template<uint32_t Mask>
        using clock_apb2 = ::zoal::arch::stm32x::bus_clock<rcc, zoal::arch::bus::cortex_apb2, Mask>;

        template<uintptr_t Address, class Clock>
        using adc = typename ::zoal::arch::stm32f3::adc<Address, Clock>;

        template<uintptr_t Address, class Clock, uint32_t PinMask>
        using port = typename ::zoal::arch::stm32x::port<Address, Clock, PinMask>;

        using port_a = port<0x48000000, clock_ahb<0x00020000>, 0xFFFF>;
        using port_b = port<0x48000400, clock_ahb<0x00040000>, 0xFFFF>;
        using port_c = port<0x48000800, clock_ahb<0x00080000>, 0xFFFF>;
        using port_d = port<0x48000C00, clock_ahb<0x00100000>, 0xFFFF>;
        using port_e = port<0x48001000, clock_ahb<0x00200000>, 0xFFFF>;
        using port_f = port<0x48001400, clock_ahb<0x00400000>, 0x0657>;

        using adc_01 = ::zoal::arch::stm32f3::adc<0x50000000, clock_ahb<0x10000000>>;
        using adc_02 = ::zoal::arch::stm32f3::adc<0x50000100, clock_ahb<0x10000000>>;
        using adc_03 = ::zoal::arch::stm32f3::adc<0x50000400, clock_ahb<0x20000000>>;
        using adc_04 = ::zoal::arch::stm32f3::adc<0x50000500, clock_ahb<0x20000000>>;

        using i2c_01 = ::zoal::arch::stm32f3::i2c<0x40005400, clock_apb1<0x00200000>>;
        using i2c_02 = ::zoal::arch::stm32f3::i2c<0x40005800, clock_apb1<0x00400000>>;

        using spi_01 = ::zoal::arch::stm32f3::spi<0x40013000, clock_apb2<0x00001000>>;
        using spi_02 = ::zoal::arch::stm32f3::spi<0x40003800, clock_apb1<0x00004000>>;
        using spi_03 = ::zoal::arch::stm32f3::spi<0x40003C00, clock_apb1<0x00008000>>;

        using timer_01 = zoal::arch::stm32f3::timer<0x40012C00, clock_apb2<0x00000800>>;
        using timer_15 = zoal::arch::stm32f3::timer<0x40014000, clock_apb2<0x00010000>>;
        using timer_16 = zoal::arch::stm32f3::timer<0x40014400, clock_apb2<0x00020000>>;
        using timer_17 = zoal::arch::stm32f3::timer<0x40014800, clock_apb2<0x00040000>>;
        using timer_02 = zoal::arch::stm32f3::timer<0x40000000, clock_apb1<0x00000001>>;
        using timer_03 = zoal::arch::stm32f3::timer<0x40000400, clock_apb1<0x00000002>>;
        using timer_04 = zoal::arch::stm32f3::timer<0x40000800, clock_apb1<0x00000004>>;
        using timer_08 = zoal::arch::stm32f3::timer<0x40013400, clock_apb2<0x00002000>>;

        using uart_04 = typename ::zoal::arch::stm32f3::usart<0x40004C00, clock_apb1<0x00080000>>;
        using uart_05 = typename ::zoal::arch::stm32f3::usart<0x40005000, clock_apb1<0x00100000>>;

        using usart_01 = typename ::zoal::arch::stm32f3::usart<0x40013800, clock_apb2<0x00004000>>;
        using usart_02 = typename ::zoal::arch::stm32f3::usart<0x40004400, clock_apb1<0x00020000>>;
        using usart_03 = typename ::zoal::arch::stm32f3::usart<0x40004800, clock_apb1<0x00040000>>;

        template<class Port, uint8_t Offset>
        using pin = typename ::zoal::gpio::pin<Port, Offset>;

        using pa_00 = pin<port_a, 0x00>;
        using pa_01 = pin<port_a, 0x01>;
        using pa_02 = pin<port_a, 0x02>;
        using pa_03 = pin<port_a, 0x03>;
        using pa_04 = pin<port_a, 0x04>;
        using pa_05 = pin<port_a, 0x05>;
        using pa_06 = pin<port_a, 0x06>;
        using pa_07 = pin<port_a, 0x07>;
        using pa_08 = pin<port_a, 0x08>;
        using pa_09 = pin<port_a, 0x09>;
        using pa_10 = pin<port_a, 0x0A>;
        using pa_11 = pin<port_a, 0x0B>;
        using pa_12 = pin<port_a, 0x0C>;
        using pa_13 = pin<port_a, 0x0D>;
        using pa_14 = pin<port_a, 0x0E>;
        using pa_15 = pin<port_a, 0x0F>;

        using pb_00 = pin<port_b, 0x00>;
        using pb_01 = pin<port_b, 0x01>;
        using pb_02 = pin<port_b, 0x02>;
        using pb_03 = pin<port_b, 0x03>;
        using pb_04 = pin<port_b, 0x04>;
        using pb_05 = pin<port_b, 0x05>;
        using pb_06 = pin<port_b, 0x06>;
        using pb_07 = pin<port_b, 0x07>;
        using pb_08 = pin<port_b, 0x08>;
        using pb_09 = pin<port_b, 0x09>;
        using pb_10 = pin<port_b, 0x0A>;
        using pb_11 = pin<port_b, 0x0B>;
        using pb_12 = pin<port_b, 0x0C>;
        using pb_13 = pin<port_b, 0x0D>;
        using pb_14 = pin<port_b, 0x0E>;
        using pb_15 = pin<port_b, 0x0F>;

        using pc_00 = pin<port_c, 0x00>;
        using pc_01 = pin<port_c, 0x01>;
        using pc_02 = pin<port_c, 0x02>;
        using pc_03 = pin<port_c, 0x03>;
        using pc_04 = pin<port_c, 0x04>;
        using pc_05 = pin<port_c, 0x05>;
        using pc_06 = pin<port_c, 0x06>;
        using pc_07 = pin<port_c, 0x07>;
        using pc_08 = pin<port_c, 0x08>;
        using pc_09 = pin<port_c, 0x09>;
        using pc_10 = pin<port_c, 0x0A>;
        using pc_11 = pin<port_c, 0x0B>;
        using pc_12 = pin<port_c, 0x0C>;
        using pc_13 = pin<port_c, 0x0D>;
        using pc_14 = pin<port_c, 0x0E>;
        using pc_15 = pin<port_c, 0x0F>;

        using pd_00 = pin<port_d, 0x00>;
        using pd_01 = pin<port_d, 0x01>;
        using pd_02 = pin<port_d, 0x02>;
        using pd_03 = pin<port_d, 0x03>;
        using pd_04 = pin<port_d, 0x04>;
        using pd_05 = pin<port_d, 0x05>;
        using pd_06 = pin<port_d, 0x06>;
        using pd_07 = pin<port_d, 0x07>;
        using pd_08 = pin<port_d, 0x08>;
        using pd_09 = pin<port_d, 0x09>;
        using pd_10 = pin<port_d, 0x0A>;
        using pd_11 = pin<port_d, 0x0B>;
        using pd_12 = pin<port_d, 0x0C>;
        using pd_13 = pin<port_d, 0x0D>;
        using pd_14 = pin<port_d, 0x0E>;
        using pd_15 = pin<port_d, 0x0F>;

        using pe_00 = pin<port_e, 0x00>;
        using pe_01 = pin<port_e, 0x01>;
        using pe_02 = pin<port_e, 0x02>;
        using pe_03 = pin<port_e, 0x03>;
        using pe_04 = pin<port_e, 0x04>;
        using pe_05 = pin<port_e, 0x05>;
        using pe_06 = pin<port_e, 0x06>;
        using pe_07 = pin<port_e, 0x07>;
        using pe_08 = pin<port_e, 0x08>;
        using pe_09 = pin<port_e, 0x09>;
        using pe_10 = pin<port_e, 0x0A>;
        using pe_11 = pin<port_e, 0x0B>;
        using pe_12 = pin<port_e, 0x0C>;
        using pe_13 = pin<port_e, 0x0D>;
        using pe_14 = pin<port_e, 0x0E>;
        using pe_15 = pin<port_e, 0x0F>;

        using pf_00 = pin<port_f, 0x00>;
        using pf_01 = pin<port_f, 0x01>;
        using pf_02 = pin<port_f, 0x02>;
        using pf_04 = pin<port_f, 0x04>;
        using pf_06 = pin<port_f, 0x06>;
        using pf_09 = pin<port_f, 0x09>;
        using pf_10 = pin<port_f, 0x0A>;

        using ports = ::zoal::ct::type_list<port_a, port_b, port_c, port_d, port_e, port_f>;
        using api = ::zoal::gpio::api;
        using mux = ::zoal::arch::stm32f3::mux<self_type>;
        using cfg = ::zoal::arch::stm32f3::cfg<self_type>;

        template<class... Module>
        using power = ::zoal::arch::power<Module...>;

        template<class... Module>
        using enable = ::zoal::arch::enable<Module...>;
    };
}}

namespace zoal { namespace metadata {
    using zoal::ct::integral_constant;
    using stm32f303vctx_sign = zoal::ct::signature<'s', 't', 'm', '3', '2', 'f', '3', '0', '3', 'v', 'c', 't', 'x'>;

    template<> // PA0 -> TIM2_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x00, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA0 -> TIM2_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x00, signal::etr> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA1 -> TIM2_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x01, signal::ch2> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA2 -> TIM2_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x02, signal::ch3> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA3 -> TIM2_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x03, signal::ch4> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA5 -> TIM2_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x05, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA5 -> TIM2_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x05, signal::etr> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA9 -> TIM2_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x09, signal::ch3> : zoal::ct::integral_constant<int, 10> {};
    template<> // PA10 -> TIM2_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x0A, signal::ch4> : zoal::ct::integral_constant<int, 10> {};
    template<> // PA15 -> TIM2_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x0F, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA15 -> TIM2_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000000, 0x0F, signal::etr> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB3 -> TIM2_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000400, 0x03, signal::ch2> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB10 -> TIM2_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000400, 0x0A, signal::ch3> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB11 -> TIM2_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000400, 0x0B, signal::ch4> : zoal::ct::integral_constant<int, 1> {};
    template<> // PD3 -> TIM2_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000C00, 0x03, signal::ch1> : zoal::ct::integral_constant<int, 2> {};
    template<> // PD3 -> TIM2_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000C00, 0x03, signal::etr> : zoal::ct::integral_constant<int, 2> {};
    template<> // PD4 -> TIM2_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000C00, 0x04, signal::ch2> : zoal::ct::integral_constant<int, 2> {};
    template<> // PD6 -> TIM2_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000C00, 0x06, signal::ch4> : zoal::ct::integral_constant<int, 2> {};
    template<> // PD7 -> TIM2_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000000, 0x48000C00, 0x07, signal::ch3> : zoal::ct::integral_constant<int, 2> {};
    template<> // PA4 -> TIM3_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000000, 0x04, signal::ch2> : zoal::ct::integral_constant<int, 2> {};
    template<> // PA6 -> TIM3_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000000, 0x06, signal::ch1> : zoal::ct::integral_constant<int, 2> {};
    template<> // PA7 -> TIM3_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000000, 0x07, signal::ch2> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB0 -> TIM3_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000400, 0x00, signal::ch3> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB1 -> TIM3_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000400, 0x01, signal::ch4> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB3 -> TIM3_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000400, 0x03, signal::etr> : zoal::ct::integral_constant<int, 10> {};
    template<> // PB4 -> TIM3_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000400, 0x04, signal::ch1> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB5 -> TIM3_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000400, 0x05, signal::ch2> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB7 -> TIM3_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000400, 0x07, signal::ch4> : zoal::ct::integral_constant<int, 10> {};
    template<> // PC6 -> TIM3_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000800, 0x06, signal::ch1> : zoal::ct::integral_constant<int, 2> {};
    template<> // PC7 -> TIM3_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000800, 0x07, signal::ch2> : zoal::ct::integral_constant<int, 2> {};
    template<> // PC8 -> TIM3_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000800, 0x08, signal::ch3> : zoal::ct::integral_constant<int, 2> {};
    template<> // PC9 -> TIM3_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000800, 0x09, signal::ch4> : zoal::ct::integral_constant<int, 2> {};
    template<> // PD2 -> TIM3_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48000C00, 0x02, signal::etr> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE2 -> TIM3_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48001000, 0x02, signal::ch1> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE3 -> TIM3_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48001000, 0x03, signal::ch2> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE4 -> TIM3_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48001000, 0x04, signal::ch3> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE5 -> TIM3_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000400, 0x48001000, 0x05, signal::ch4> : zoal::ct::integral_constant<int, 2> {};
    template<> // PA8 -> TIM4_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000000, 0x08, signal::etr> : zoal::ct::integral_constant<int, 10> {};
    template<> // PA11 -> TIM4_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000000, 0x0B, signal::ch1> : zoal::ct::integral_constant<int, 10> {};
    template<> // PA12 -> TIM4_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000000, 0x0C, signal::ch2> : zoal::ct::integral_constant<int, 10> {};
    template<> // PA13 -> TIM4_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000000, 0x0D, signal::ch3> : zoal::ct::integral_constant<int, 10> {};
    template<> // PB3 -> TIM4_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000400, 0x03, signal::etr> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB6 -> TIM4_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000400, 0x06, signal::ch1> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB7 -> TIM4_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000400, 0x07, signal::ch2> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB8 -> TIM4_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000400, 0x08, signal::ch3> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB9 -> TIM4_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000400, 0x09, signal::ch4> : zoal::ct::integral_constant<int, 2> {};
    template<> // PD12 -> TIM4_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000C00, 0x0C, signal::ch1> : zoal::ct::integral_constant<int, 2> {};
    template<> // PD13 -> TIM4_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000C00, 0x0D, signal::ch2> : zoal::ct::integral_constant<int, 2> {};
    template<> // PD14 -> TIM4_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000C00, 0x0E, signal::ch3> : zoal::ct::integral_constant<int, 2> {};
    template<> // PD15 -> TIM4_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48000C00, 0x0F, signal::ch4> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE0 -> TIM4_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48001000, 0x00, signal::etr> : zoal::ct::integral_constant<int, 2> {};
    template<> // PF6 -> TIM4_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40000800, 0x48001400, 0x06, signal::ch4> : zoal::ct::integral_constant<int, 2> {};
    template<> // PA8 -> I2S2_MCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000000, 0x08, signal::mck> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB12 -> SPI2_NSS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000400, 0x0C, signal::nss> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB12 -> I2S2_WS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000400, 0x0C, signal::ws> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB13 -> I2S2_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000400, 0x0D, signal::ck> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB13 -> SPI2_SCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000400, 0x0D, signal::sck> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB14 -> SPI2_MISO
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000400, 0x0E, signal::miso> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB14 -> I2S2_ext_SD
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000400, 0x0E, signal::sd> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB15 -> SPI2_MOSI
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000400, 0x0F, signal::mosi> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB15 -> I2S2_SD
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000400, 0x0F, signal::sd> : zoal::ct::integral_constant<int, 5> {};
    template<> // PC6 -> I2S2_MCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000800, 0x06, signal::mck> : zoal::ct::integral_constant<int, 6> {};
    template<> // PD15 -> SPI2_NSS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48000C00, 0x0F, signal::nss> : zoal::ct::integral_constant<int, 6> {};
    template<> // PF9 -> SPI2_SCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48001400, 0x09, signal::sck> : zoal::ct::integral_constant<int, 5> {};
    template<> // PF10 -> SPI2_SCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003800, 0x48001400, 0x0A, signal::sck> : zoal::ct::integral_constant<int, 5> {};
    template<> // PA4 -> SPI3_NSS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000000, 0x04, signal::nss> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA4 -> I2S3_WS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000000, 0x04, signal::ws> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA9 -> I2S3_MCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000000, 0x09, signal::mck> : zoal::ct::integral_constant<int, 5> {};
    template<> // PA15 -> SPI3_NSS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000000, 0x0F, signal::nss> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA15 -> I2S3_WS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000000, 0x0F, signal::ws> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB3 -> I2S3_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000400, 0x03, signal::ck> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB3 -> SPI3_SCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000400, 0x03, signal::sck> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB4 -> SPI3_MISO
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000400, 0x04, signal::miso> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB4 -> I2S3_ext_SD
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000400, 0x04, signal::sd> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB5 -> SPI3_MOSI
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000400, 0x05, signal::mosi> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB5 -> I2S3_SD
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000400, 0x05, signal::sd> : zoal::ct::integral_constant<int, 6> {};
    template<> // PC7 -> I2S3_MCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000800, 0x07, signal::mck> : zoal::ct::integral_constant<int, 6> {};
    template<> // PC10 -> I2S3_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000800, 0x0A, signal::ck> : zoal::ct::integral_constant<int, 6> {};
    template<> // PC10 -> SPI3_SCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000800, 0x0A, signal::sck> : zoal::ct::integral_constant<int, 6> {};
    template<> // PC11 -> SPI3_MISO
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000800, 0x0B, signal::miso> : zoal::ct::integral_constant<int, 6> {};
    template<> // PC11 -> I2S3_ext_SD
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000800, 0x0B, signal::sd> : zoal::ct::integral_constant<int, 6> {};
    template<> // PC12 -> SPI3_MOSI
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000800, 0x0C, signal::mosi> : zoal::ct::integral_constant<int, 6> {};
    template<> // PC12 -> I2S3_SD
    struct stm32_signal_map<stm32f303vctx_sign, 0x40003C00, 0x48000800, 0x0C, signal::sd> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA0 -> USART2_CTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000000, 0x00, signal::cts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA1 -> USART2_DE
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000000, 0x01, signal::de> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA1 -> USART2_RTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000000, 0x01, signal::rts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA2 -> USART2_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000000, 0x02, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA3 -> USART2_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000000, 0x03, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA4 -> USART2_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000000, 0x04, signal::ck> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA14 -> USART2_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000000, 0x0E, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA15 -> USART2_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000000, 0x0F, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB3 -> USART2_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000400, 0x03, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB4 -> USART2_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000400, 0x04, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB5 -> USART2_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000400, 0x05, signal::ck> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD3 -> USART2_CTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000C00, 0x03, signal::cts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD4 -> USART2_DE
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000C00, 0x04, signal::de> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD4 -> USART2_RTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000C00, 0x04, signal::rts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD5 -> USART2_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000C00, 0x05, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD6 -> USART2_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000C00, 0x06, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD7 -> USART2_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004400, 0x48000C00, 0x07, signal::ck> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA13 -> USART3_CTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000000, 0x0D, signal::cts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB10 -> USART3_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000400, 0x0A, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB11 -> USART3_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000400, 0x0B, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB12 -> USART3_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000400, 0x0C, signal::ck> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB13 -> USART3_CTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000400, 0x0D, signal::cts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB14 -> USART3_DE
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000400, 0x0E, signal::de> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB14 -> USART3_RTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000400, 0x0E, signal::rts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PC10 -> USART3_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000800, 0x0A, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PC11 -> USART3_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000800, 0x0B, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PC12 -> USART3_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000800, 0x0C, signal::ck> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD8 -> USART3_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000C00, 0x08, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD9 -> USART3_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000C00, 0x09, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD10 -> USART3_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000C00, 0x0A, signal::ck> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD11 -> USART3_CTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000C00, 0x0B, signal::cts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD12 -> USART3_DE
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000C00, 0x0C, signal::de> : zoal::ct::integral_constant<int, 7> {};
    template<> // PD12 -> USART3_RTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48000C00, 0x0C, signal::rts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PE15 -> USART3_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48001000, 0x0F, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PF6 -> USART3_DE
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48001400, 0x06, signal::de> : zoal::ct::integral_constant<int, 7> {};
    template<> // PF6 -> USART3_RTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004800, 0x48001400, 0x06, signal::rts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PC10 -> UART4_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004C00, 0x48000800, 0x0A, signal::tx> : zoal::ct::integral_constant<int, 5> {};
    template<> // PC11 -> UART4_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40004C00, 0x48000800, 0x0B, signal::rx> : zoal::ct::integral_constant<int, 5> {};
    template<> // PC12 -> UART5_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005000, 0x48000800, 0x0C, signal::tx> : zoal::ct::integral_constant<int, 5> {};
    template<> // PD2 -> UART5_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005000, 0x48000C00, 0x02, signal::rx> : zoal::ct::integral_constant<int, 5> {};
    template<> // PA14 -> I2C1_SDA
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005400, 0x48000000, 0x0E, signal::sda> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA15 -> I2C1_SCL
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005400, 0x48000000, 0x0F, signal::scl> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB5 -> I2C1_SMBA
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005400, 0x48000400, 0x05, signal::smba> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB6 -> I2C1_SCL
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005400, 0x48000400, 0x06, signal::scl> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB7 -> I2C1_SDA
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005400, 0x48000400, 0x07, signal::sda> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB8 -> I2C1_SCL
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005400, 0x48000400, 0x08, signal::scl> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB9 -> I2C1_SDA
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005400, 0x48000400, 0x09, signal::sda> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA8 -> I2C2_SMBA
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005800, 0x48000000, 0x08, signal::smba> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA9 -> I2C2_SCL
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005800, 0x48000000, 0x09, signal::scl> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA10 -> I2C2_SDA
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005800, 0x48000000, 0x0A, signal::sda> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB12 -> I2C2_SMBA
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005800, 0x48000400, 0x0C, signal::smba> : zoal::ct::integral_constant<int, 4> {};
    template<> // PF0-OSC_IN -> I2C2_SDA
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005800, 0x48001400, 0x00, signal::sda> : zoal::ct::integral_constant<int, 4> {};
    template<> // PF1-OSC_OUT -> I2C2_SCL
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005800, 0x48001400, 0x01, signal::scl> : zoal::ct::integral_constant<int, 4> {};
    template<> // PF6 -> I2C2_SCL
    struct stm32_signal_map<stm32f303vctx_sign, 0x40005800, 0x48001400, 0x06, signal::scl> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA6 -> TIM1_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x06, signal::bkin> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA7 -> TIM1_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x07, signal::ch1n> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA8 -> TIM1_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x08, signal::ch1> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA9 -> TIM1_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x09, signal::ch2> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA10 -> TIM1_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x0A, signal::ch3> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA11 -> TIM1_BKIN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x0B, signal::bkin2> : zoal::ct::integral_constant<int, 12> {};
    template<> // PA11 -> TIM1_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x0B, signal::ch1n> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA11 -> TIM1_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x0B, signal::ch4> : zoal::ct::integral_constant<int, 11> {};
    template<> // PA12 -> TIM1_CH2N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x0C, signal::ch2n> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA12 -> TIM1_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x0C, signal::etr> : zoal::ct::integral_constant<int, 11> {};
    template<> // PA14 -> TIM1_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x0E, signal::bkin> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA15 -> TIM1_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000000, 0x0F, signal::bkin> : zoal::ct::integral_constant<int, 9> {};
    template<> // PB0 -> TIM1_CH2N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000400, 0x00, signal::ch2n> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB1 -> TIM1_CH3N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000400, 0x01, signal::ch3n> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB8 -> TIM1_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000400, 0x08, signal::bkin> : zoal::ct::integral_constant<int, 12> {};
    template<> // PB12 -> TIM1_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000400, 0x0C, signal::bkin> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB13 -> TIM1_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000400, 0x0D, signal::ch1n> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB14 -> TIM1_CH2N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000400, 0x0E, signal::ch2n> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB15 -> TIM1_CH3N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000400, 0x0F, signal::ch3n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PC3 -> TIM1_BKIN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000800, 0x03, signal::bkin2> : zoal::ct::integral_constant<int, 6> {};
    template<> // PC13 -> TIM1_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48000800, 0x0D, signal::ch1n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PE7 -> TIM1_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x07, signal::etr> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE8 -> TIM1_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x08, signal::ch1n> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE9 -> TIM1_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x09, signal::ch1> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE10 -> TIM1_CH2N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x0A, signal::ch2n> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE11 -> TIM1_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x0B, signal::ch2> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE12 -> TIM1_CH3N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x0C, signal::ch3n> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE13 -> TIM1_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x0D, signal::ch3> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE14 -> TIM1_BKIN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x0E, signal::bkin2> : zoal::ct::integral_constant<int, 6> {};
    template<> // PE14 -> TIM1_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x0E, signal::ch4> : zoal::ct::integral_constant<int, 2> {};
    template<> // PE15 -> TIM1_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001000, 0x0F, signal::bkin> : zoal::ct::integral_constant<int, 2> {};
    template<> // PF0-OSC_IN -> TIM1_CH3N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40012C00, 0x48001400, 0x00, signal::ch3n> : zoal::ct::integral_constant<int, 6> {};
    template<> // PA4 -> SPI1_NSS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013000, 0x48000000, 0x04, signal::nss> : zoal::ct::integral_constant<int, 5> {};
    template<> // PA5 -> SPI1_SCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013000, 0x48000000, 0x05, signal::sck> : zoal::ct::integral_constant<int, 5> {};
    template<> // PA6 -> SPI1_MISO
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013000, 0x48000000, 0x06, signal::miso> : zoal::ct::integral_constant<int, 5> {};
    template<> // PA7 -> SPI1_MOSI
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013000, 0x48000000, 0x07, signal::mosi> : zoal::ct::integral_constant<int, 5> {};
    template<> // PA15 -> SPI1_NSS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013000, 0x48000000, 0x0F, signal::nss> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB3 -> SPI1_SCK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013000, 0x48000400, 0x03, signal::sck> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB4 -> SPI1_MISO
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013000, 0x48000400, 0x04, signal::miso> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB5 -> SPI1_MOSI
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013000, 0x48000400, 0x05, signal::mosi> : zoal::ct::integral_constant<int, 5> {};
    template<> // PC9 -> I2S_CKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013000, 0x48000800, 0x09, signal::ckin> : zoal::ct::integral_constant<int, 5> {};
    template<> // PA0 -> TIM8_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000000, 0x00, signal::bkin> : zoal::ct::integral_constant<int, 9> {};
    template<> // PA0 -> TIM8_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000000, 0x00, signal::etr> : zoal::ct::integral_constant<int, 10> {};
    template<> // PA6 -> TIM8_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000000, 0x06, signal::bkin> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA7 -> TIM8_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000000, 0x07, signal::ch1n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA10 -> TIM8_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000000, 0x0A, signal::bkin> : zoal::ct::integral_constant<int, 11> {};
    template<> // PA14 -> TIM8_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000000, 0x0E, signal::ch2> : zoal::ct::integral_constant<int, 5> {};
    template<> // PA15 -> TIM8_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000000, 0x0F, signal::ch1> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB0 -> TIM8_CH2N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x00, signal::ch2n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB1 -> TIM8_CH3N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x01, signal::ch3n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB3 -> TIM8_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x03, signal::ch1n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB4 -> TIM8_CH2N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x04, signal::ch2n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PB5 -> TIM8_CH3N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x05, signal::ch3n> : zoal::ct::integral_constant<int, 3> {};
    template<> // PB6 -> TIM8_BKIN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x06, signal::bkin2> : zoal::ct::integral_constant<int, 10> {};
    template<> // PB6 -> TIM8_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x06, signal::ch1> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB6 -> TIM8_ETR
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x06, signal::etr> : zoal::ct::integral_constant<int, 6> {};
    template<> // PB7 -> TIM8_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x07, signal::bkin> : zoal::ct::integral_constant<int, 5> {};
    template<> // PB8 -> TIM8_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x08, signal::ch2> : zoal::ct::integral_constant<int, 10> {};
    template<> // PB9 -> TIM8_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000400, 0x09, signal::ch3> : zoal::ct::integral_constant<int, 10> {};
    template<> // PC6 -> TIM8_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000800, 0x06, signal::ch1> : zoal::ct::integral_constant<int, 4> {};
    template<> // PC7 -> TIM8_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000800, 0x07, signal::ch2> : zoal::ct::integral_constant<int, 4> {};
    template<> // PC8 -> TIM8_CH3
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000800, 0x08, signal::ch3> : zoal::ct::integral_constant<int, 4> {};
    template<> // PC9 -> TIM8_BKIN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000800, 0x09, signal::bkin2> : zoal::ct::integral_constant<int, 6> {};
    template<> // PC9 -> TIM8_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000800, 0x09, signal::ch4> : zoal::ct::integral_constant<int, 4> {};
    template<> // PC10 -> TIM8_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000800, 0x0A, signal::ch1n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PC11 -> TIM8_CH2N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000800, 0x0B, signal::ch2n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PC12 -> TIM8_CH3N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000800, 0x0C, signal::ch3n> : zoal::ct::integral_constant<int, 4> {};
    template<> // PD1 -> TIM8_BKIN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000C00, 0x01, signal::bkin2> : zoal::ct::integral_constant<int, 6> {};
    template<> // PD1 -> TIM8_CH4
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000C00, 0x01, signal::ch4> : zoal::ct::integral_constant<int, 4> {};
    template<> // PD2 -> TIM8_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013400, 0x48000C00, 0x02, signal::bkin> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA8 -> USART1_CK
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000000, 0x08, signal::ck> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA9 -> USART1_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000000, 0x09, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA10 -> USART1_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000000, 0x0A, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA11 -> USART1_CTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000000, 0x0B, signal::cts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA12 -> USART1_DE
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000000, 0x0C, signal::de> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA12 -> USART1_RTS
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000000, 0x0C, signal::rts> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB6 -> USART1_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000400, 0x06, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PB7 -> USART1_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000400, 0x07, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PC4 -> USART1_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000800, 0x04, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PC5 -> USART1_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48000800, 0x05, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PE0 -> USART1_TX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48001000, 0x00, signal::tx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PE1 -> USART1_RX
    struct stm32_signal_map<stm32f303vctx_sign, 0x40013800, 0x48001000, 0x01, signal::rx> : zoal::ct::integral_constant<int, 7> {};
    template<> // PA1 -> TIM15_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014000, 0x48000000, 0x01, signal::ch1n> : zoal::ct::integral_constant<int, 9> {};
    template<> // PA2 -> TIM15_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014000, 0x48000000, 0x02, signal::ch1> : zoal::ct::integral_constant<int, 9> {};
    template<> // PA3 -> TIM15_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014000, 0x48000000, 0x03, signal::ch2> : zoal::ct::integral_constant<int, 9> {};
    template<> // PA9 -> TIM15_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014000, 0x48000000, 0x09, signal::bkin> : zoal::ct::integral_constant<int, 9> {};
    template<> // PB14 -> TIM15_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014000, 0x48000400, 0x0E, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB15 -> TIM15_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014000, 0x48000400, 0x0F, signal::ch1n> : zoal::ct::integral_constant<int, 2> {};
    template<> // PB15 -> TIM15_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014000, 0x48000400, 0x0F, signal::ch2> : zoal::ct::integral_constant<int, 1> {};
    template<> // PF9 -> TIM15_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014000, 0x48001400, 0x09, signal::ch1> : zoal::ct::integral_constant<int, 3> {};
    template<> // PF10 -> TIM15_CH2
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014000, 0x48001400, 0x0A, signal::ch2> : zoal::ct::integral_constant<int, 3> {};
    template<> // PA6 -> TIM16_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014400, 0x48000000, 0x06, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA12 -> TIM16_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014400, 0x48000000, 0x0C, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA13 -> TIM16_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014400, 0x48000000, 0x0D, signal::ch1n> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB4 -> TIM16_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014400, 0x48000400, 0x04, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB5 -> TIM16_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014400, 0x48000400, 0x05, signal::bkin> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB6 -> TIM16_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014400, 0x48000400, 0x06, signal::ch1n> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB8 -> TIM16_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014400, 0x48000400, 0x08, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PE0 -> TIM16_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014400, 0x48001000, 0x00, signal::ch1> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA7 -> TIM17_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014800, 0x48000000, 0x07, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PA10 -> TIM17_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014800, 0x48000000, 0x0A, signal::bkin> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB4 -> TIM17_BKIN
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014800, 0x48000400, 0x04, signal::bkin> : zoal::ct::integral_constant<int, 10> {};
    template<> // PB5 -> TIM17_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014800, 0x48000400, 0x05, signal::ch1> : zoal::ct::integral_constant<int, 10> {};
    template<> // PB7 -> TIM17_CH1N
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014800, 0x48000400, 0x07, signal::ch1n> : zoal::ct::integral_constant<int, 1> {};
    template<> // PB9 -> TIM17_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014800, 0x48000400, 0x09, signal::ch1> : zoal::ct::integral_constant<int, 1> {};
    template<> // PE1 -> TIM17_CH1
    struct stm32_signal_map<stm32f303vctx_sign, 0x40014800, 0x48001000, 0x01, signal::ch1> : zoal::ct::integral_constant<int, 4> {};
    template<> // PA0 -> ADC1_IN1
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000000, 0x00, signal::in1> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA1 -> ADC1_IN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000000, 0x01, signal::in2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA2 -> ADC1_IN3
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000000, 0x02, signal::in3> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA3 -> ADC1_IN4
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000000, 0x03, signal::in4> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA11 -> ADC1_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000000, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA15 -> ADC1_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000000, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB11 -> ADC1_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000400, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB15 -> ADC1_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000400, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC0 -> ADC1_IN6
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000800, 0x00, signal::in6> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC1 -> ADC1_IN7
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000800, 0x01, signal::in7> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC2 -> ADC1_IN8
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000800, 0x02, signal::in8> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC3 -> ADC1_IN9
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000800, 0x03, signal::in9> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC11 -> ADC1_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000800, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC15-OSC32_OUT -> ADC1_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000800, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD11 -> ADC1_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000C00, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD15 -> ADC1_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48000C00, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE11 -> ADC1_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48001000, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE15 -> ADC1_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48001000, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PF2 -> ADC1_IN10
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48001400, 0x02, signal::in10> : zoal::ct::integral_constant<int, 0> {};
    template<> // PF4 -> ADC1_IN5
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000000, 0x48001400, 0x04, signal::in5> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA4 -> ADC2_IN1
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000000, 0x04, signal::in1> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA5 -> ADC2_IN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000000, 0x05, signal::in2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA6 -> ADC2_IN3
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000000, 0x06, signal::in3> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA7 -> ADC2_IN4
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000000, 0x07, signal::in4> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA11 -> ADC2_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000000, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA15 -> ADC2_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000000, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB2 -> ADC2_IN12
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000400, 0x02, signal::in12> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB11 -> ADC2_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000400, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB15 -> ADC2_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000400, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC0 -> ADC2_IN6
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000800, 0x00, signal::in6> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC1 -> ADC2_IN7
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000800, 0x01, signal::in7> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC2 -> ADC2_IN8
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000800, 0x02, signal::in8> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC3 -> ADC2_IN9
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000800, 0x03, signal::in9> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC4 -> ADC2_IN5
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000800, 0x04, signal::in5> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC5 -> ADC2_IN11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000800, 0x05, signal::in11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC11 -> ADC2_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000800, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC15-OSC32_OUT -> ADC2_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000800, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD11 -> ADC2_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000C00, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD15 -> ADC2_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48000C00, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE11 -> ADC2_EXTI11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48001000, 0x0B, signal::exti11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE15 -> ADC2_EXTI15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48001000, 0x0F, signal::exti15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PF2 -> ADC2_IN10
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000100, 0x48001400, 0x02, signal::in10> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA2 -> ADC3_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000000, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB0 -> ADC3_IN12
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000400, 0x00, signal::in12> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB1 -> ADC3_IN1
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000400, 0x01, signal::in1> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB2 -> ADC3_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000400, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB13 -> ADC3_IN5
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000400, 0x0D, signal::in5> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC2 -> ADC3_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000800, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD2 -> ADC3_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000C00, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD10 -> ADC3_IN7
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000C00, 0x0A, signal::in7> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD11 -> ADC3_IN8
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000C00, 0x0B, signal::in8> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD12 -> ADC3_IN9
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000C00, 0x0C, signal::in9> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD13 -> ADC3_IN10
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000C00, 0x0D, signal::in10> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD14 -> ADC3_IN11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48000C00, 0x0E, signal::in11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE2 -> ADC3_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48001000, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE7 -> ADC3_IN13
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48001000, 0x07, signal::in13> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE8 -> ADC3_IN6
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48001000, 0x08, signal::in6> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE9 -> ADC3_IN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48001000, 0x09, signal::in2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE10 -> ADC3_IN14
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48001000, 0x0A, signal::in14> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE11 -> ADC3_IN15
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48001000, 0x0B, signal::in15> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE12 -> ADC3_IN16
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48001000, 0x0C, signal::in16> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE13 -> ADC3_IN3
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48001000, 0x0D, signal::in3> : zoal::ct::integral_constant<int, 0> {};
    template<> // PF2 -> ADC3_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000400, 0x48001400, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PA2 -> ADC4_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000000, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB2 -> ADC4_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000400, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB12 -> ADC4_IN3
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000400, 0x0C, signal::in3> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB14 -> ADC4_IN4
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000400, 0x0E, signal::in4> : zoal::ct::integral_constant<int, 0> {};
    template<> // PB15 -> ADC4_IN5
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000400, 0x0F, signal::in5> : zoal::ct::integral_constant<int, 0> {};
    template<> // PC2 -> ADC4_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000800, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD2 -> ADC4_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000C00, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD8 -> ADC4_IN12
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000C00, 0x08, signal::in12> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD9 -> ADC4_IN13
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000C00, 0x09, signal::in13> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD10 -> ADC4_IN7
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000C00, 0x0A, signal::in7> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD11 -> ADC4_IN8
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000C00, 0x0B, signal::in8> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD12 -> ADC4_IN9
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000C00, 0x0C, signal::in9> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD13 -> ADC4_IN10
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000C00, 0x0D, signal::in10> : zoal::ct::integral_constant<int, 0> {};
    template<> // PD14 -> ADC4_IN11
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48000C00, 0x0E, signal::in11> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE2 -> ADC4_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48001000, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE8 -> ADC4_IN6
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48001000, 0x08, signal::in6> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE14 -> ADC4_IN1
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48001000, 0x0E, signal::in1> : zoal::ct::integral_constant<int, 0> {};
    template<> // PE15 -> ADC4_IN2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48001000, 0x0F, signal::in2> : zoal::ct::integral_constant<int, 0> {};
    template<> // PF2 -> ADC4_EXTI2
    struct stm32_signal_map<stm32f303vctx_sign, 0x50000500, 0x48001400, 0x02, signal::exti2> : zoal::ct::integral_constant<int, 0> {};
}}

#endif
