/**
 * Autogenerated file. Do not modify manually.
 */
#ifndef ZOAL_MCU_STM32F303_RD_RE_HPP
#define ZOAL_MCU_STM32F303_RD_RE_HPP

#include <stdint.h>
#include <zoal/arch/cortex/stm32f3/adc.hpp>
#include <zoal/arch/cortex/stm32f3/adc_common_regs.hpp>
#include <zoal/arch/cortex/stm32f3/general_purpose_timer.hpp>
#include <zoal/arch/cortex/stm32f3/spi.hpp>
#include <zoal/arch/cortex/stm32x/bus_clock.hpp>
#include <zoal/arch/cortex/stm32x/cfg.hpp>
#include <zoal/arch/cortex/stm32x/mux.hpp>
#include <zoal/arch/cortex/stm32x/port.hpp>
#include <zoal/arch/cortex/stm32x/reset_and_clock_control.hpp>
#include <zoal/arch/cortex/stm32x/usart.hpp>
#include <zoal/arch/enable.hpp>
#include <zoal/arch/power.hpp>
#include <zoal/gpio/api.hpp>

namespace zoal { namespace mcu {
    template<uint32_t HighSpeedExternalOscillator = 8000000, uint8_t PhaseLockedLoop = 9>
    class stm32f303_rd_re {
    public:
        static constexpr auto hse = HighSpeedExternalOscillator;
        static constexpr auto pll = PhaseLockedLoop;
        static constexpr auto frequency = hse * pll;

        using self_type = stm32f303_rd_re<hse, pll>;
        using rcc = ::zoal::arch::stm32x::reset_and_clock_control<>;

        template<uint32_t Mask>
        using clock_ahb = ::zoal::arch::stm32x::bus_clock<rcc, zoal::arch::bus::cortex_ahb, Mask>;

        template<uint32_t Mask>
        using clock_apb1 = ::zoal::arch::stm32x::bus_clock<rcc, zoal::arch::bus::cortex_apb1, Mask>;

        template<uint32_t Mask>
        using clock_apb2 = ::zoal::arch::stm32x::bus_clock<rcc, zoal::arch::bus::cortex_apb2, Mask>;

        template<uintptr_t Address, uint8_t N, class Clock>
        using adc = typename ::zoal::arch::stm32f3::adc<Address, N, Clock>;

        template<uintptr_t Address, class Clock, uint32_t PinMask>
        using port = typename ::zoal::arch::stm32x::port<Address, Clock, PinMask>;

        using port_a = port<0x48000000, clock_ahb<0x00020000>, 0xFFFF>;
        using port_b = port<0x48000400, clock_ahb<0x00040000>, 0xFFFF>;
        using port_c = port<0x48000800, clock_ahb<0x00080000>, 0xFFFF>;
        using port_d = port<0x48000C00, clock_ahb<0x00100000>, 0x0004>;
        using port_f = port<0x48001400, clock_ahb<0x00400000>, 0x0003>;

        using adc_01 = adc<0x50000000, 1, clock_ahb<0x10000000>>;
        using adc_02 = adc<0x50000100, 2, clock_ahb<0x10000000>>;
        using adc_03 = adc<0x50000400, 3, clock_ahb<0x20000000>>;
        using adc_04 = adc<0x50000500, 4, clock_ahb<0x20000000>>;

        using timer_02 = zoal::arch::stm32f3::general_purpose_timer<0x40000000, 2, clock_apb1<0x00000001>>;
        using timer_03 = zoal::arch::stm32f3::general_purpose_timer<0x40000400, 3, clock_apb1<0x00000002>>;
        using timer_04 = zoal::arch::stm32f3::general_purpose_timer<0x40000800, 4, clock_apb1<0x00000004>>;

        template<class Buffer>
        using usart_01 = typename ::zoal::arch::stm32x::usart<0x40013800, 1, Buffer, clock_apb2<0x00004000>>;

        template<class Buffer>
        using usart_02 = typename ::zoal::arch::stm32x::usart<0x40004400, 2, Buffer, clock_apb1<0x00020000>>;

        template<class Buffer>
        using usart_03 = typename ::zoal::arch::stm32x::usart<0x40004800, 3, Buffer, clock_apb1<0x00040000>>;

        template<class Port, uint8_t Offset>
        using pin = typename ::zoal::gpio::pin<Port, Offset>;

        using pa_00 = pin<port_a, 0x00>;
        using pa_01 = pin<port_a, 0x01>;
        using pa_02 = pin<port_a, 0x02>;
        using pa_03 = pin<port_a, 0x03>;
        using pa_04 = pin<port_a, 0x04>;
        using pa_05 = pin<port_a, 0x05>;
        using pa_06 = pin<port_a, 0x06>;
        using pa_07 = pin<port_a, 0x07>;
        using pa_08 = pin<port_a, 0x08>;
        using pa_09 = pin<port_a, 0x09>;
        using pa_10 = pin<port_a, 0x0A>;
        using pa_11 = pin<port_a, 0x0B>;
        using pa_12 = pin<port_a, 0x0C>;
        using pa_13 = pin<port_a, 0x0D>;
        using pa_14 = pin<port_a, 0x0E>;
        using pa_15 = pin<port_a, 0x0F>;

        using pb_00 = pin<port_b, 0x00>;
        using pb_01 = pin<port_b, 0x01>;
        using pb_02 = pin<port_b, 0x02>;
        using pb_03 = pin<port_b, 0x03>;
        using pb_04 = pin<port_b, 0x04>;
        using pb_05 = pin<port_b, 0x05>;
        using pb_06 = pin<port_b, 0x06>;
        using pb_07 = pin<port_b, 0x07>;
        using pb_08 = pin<port_b, 0x08>;
        using pb_09 = pin<port_b, 0x09>;
        using pb_10 = pin<port_b, 0x0A>;
        using pb_11 = pin<port_b, 0x0B>;
        using pb_12 = pin<port_b, 0x0C>;
        using pb_13 = pin<port_b, 0x0D>;
        using pb_14 = pin<port_b, 0x0E>;
        using pb_15 = pin<port_b, 0x0F>;

        using pc_00 = pin<port_c, 0x00>;
        using pc_01 = pin<port_c, 0x01>;
        using pc_02 = pin<port_c, 0x02>;
        using pc_03 = pin<port_c, 0x03>;
        using pc_04 = pin<port_c, 0x04>;
        using pc_05 = pin<port_c, 0x05>;
        using pc_06 = pin<port_c, 0x06>;
        using pc_07 = pin<port_c, 0x07>;
        using pc_08 = pin<port_c, 0x08>;
        using pc_09 = pin<port_c, 0x09>;
        using pc_10 = pin<port_c, 0x0A>;
        using pc_11 = pin<port_c, 0x0B>;
        using pc_12 = pin<port_c, 0x0C>;
        using pc_13 = pin<port_c, 0x0D>;
        using pc_14 = pin<port_c, 0x0E>;
        using pc_15 = pin<port_c, 0x0F>;

        using pd_02 = pin<port_d, 0x02>;

        using pf_00 = pin<port_f, 0x00>;
        using pf_01 = pin<port_f, 0x01>;

        using ports = ::zoal::ct::type_list<port_a, port_b, port_c, port_d, port_f>;
        using api = ::zoal::gpio::api<ports>;
        using mux = ::zoal::arch::stm32x::mux<self_type>;
        using cfg = ::zoal::arch::stm32x::cfg<self_type>;

        template<class... Module>
        using power = ::zoal::arch::power<Module...>;

        template<class... Module>
        using enable = ::zoal::arch::enable<Module...>;
    };
}}

namespace zoal { namespace metadata {
    using zoal::ct::integral_constant;

}}

#endif
