#include "constants.hpp"

const char *zoal_ascii_logo = "  __________          _\r\n"
                              " |___  / __ \\   /\\   | |\r\n"
                              "    / / |  | | /  \\  | |\r\n"
                              "   / /| |  | |/ /\\ \\ | |\r\n"
                              "  / /_| |__| / ____ \\| |____\r\n"
                              " /_____\\____/_/    \\_\\______|\r\n"
                              "\r\n";

const char *help_message = "ZOAL STM32F401 FreeRTOS Demo Application\r\n"
                           "Commands: \r\n"
                           " adc\t\r\n"
                           " help\t\r\n"
                           " i2c\t\r\n"
                           " pwm\t\r\n"
                           " pwm_off\t\r\n"
                           " pwm_on\t\r\n"
                           " ticks\t\r\n"
                           " time_print\t\r\n"
                           " time_set\t\r\n"
                           " timer\t\r\n"
                           " w25q_erase_chip\t\r\n"
                           " w25q_erase_sector\t\r\n"
                           " w25q_read\t\r\n"
                           " w25q_write\t\r\n";
